# Generated by Django 5.1.4 on 2025-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buraco',
            name='tamanho',
            field=models.SmallIntegerField(default=0),
        ),
    ]
