# Generated by Django 5.1.4 on 2025-03-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0002_buraco_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='buraco',
            name='endereco',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
