# Generated by Django 5.1.4 on 2025-03-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0003_buraco_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraco',
            name='tamanho',
            field=models.SmallIntegerField(default=1),
        ),
    ]
