# Generated by Django 6.0.4 on 2026-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0006_comentario_like_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='buraco',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='buracos/'),
        ),
    ]
