# Generated by Django 6.0.4 on 2026-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0007_buraco_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buraco',
            name='url_imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
