# Generated by Django 6.0.4 on 2026-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0009_comentario_resposta_de_likecomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='buraco',
            name='status',
            field=models.CharField(choices=[('nao_arrumado', 'Ainda nao foi arrumado'), ('em_obra', 'Em obra'), ('arrumado', 'Ja arrumado')], default='nao_arrumado', max_length=20),
        ),
    ]
