# Generated by Django 6.0.4 on 2026-05-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buracos', '0009_comentario_resposta_de_likecomentario'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='buracos.comentario'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('like', 'Curtida'), ('like_comentario', 'Curtida em comentario'), ('comentario', 'Comentario'), ('resposta_comentario', 'Resposta em comentario'), ('remocao', 'Remocao')], max_length=20),
        ),
    ]
