# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0002_notificacao_comentario_alter_notificacao_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("like", "Curtida"),
                    ("like_comentario", "Curtida em comentario"),
                    ("comentario", "Comentario"),
                    ("resposta_comentario", "Resposta em comentario"),
                    ("status", "Status"),
                    ("remocao", "Remocao"),
                ],
                max_length=20,
            ),
        ),
    ]
